version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
      python: 3.8
    commands:
      - yarn --version
      - yarn global add serverless
      - serverless -v 
      - sls plugin install -n serverless-python-requirements
      - pip install --upgrade pip
      - pip install opencv-python
      - pip install Pillow
  build:
    commands:
      - serverless deploy
