version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
      python: 3.7
    commands:
      - yarn --version
      - yarn global add serverless
      - serverless -v 
      - sls plugin install -n serverless-python-requirements
      - pip install --upgrade pip
      - pip install -r requirements.txt
      - pip show opencv-python
      - pip show Pillow
  build:
    commands:
      - serverless deploy
